name: CI

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes
  workflow_dispatch:  # Allows manual trigger via GitHub Actions UI

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use the secret you created
        run: |
          echo " " >> README.md  # Add a space to README to trigger commit
          git config user.name "collegeid"  # Replace with your username
          git config user.email "vjhunter23@gmail.com"  # Replace with your email
          git add .
          git commit -m "Always green!"
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/collegeid/collegeid.git
          git push origin main  # Push to the main branch (or the relevant branch)
